name: Release Kibana Reports Artifacts

on:
  push:
    tags:
      - "v*"

env:
  PLUGIN_NAME: opendistroReportsKibana
  OD_VERSION: 1.12.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Plugin
        uses: actions/checkout@v1

      - name: Checkout Kibana
        uses: actions/checkout@v1
        with:
          repository: elastic/kibana
          ref: v7.10.0
          path: kibana-reports/kibana

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.22.1"

      - name: Move Kibana Reports to Plugins Dir
        run: mv kibana-reports kibana/plugins/opendistroReportsKibana

      - name: Kibana Plugin Bootstrap
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cd kibana/plugins/opendistroReportsKibana; yarn kbn bootstrap

      - name: Test
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: cd kibana/plugins/opendistroReportsKibana; yarn test

      - name: Build Artifact
        run: |
          cd kibana/plugins/opendistroReportsKibana
          yarn build

          cd build
          mkdir -p ./{linux,windows}/kibana/opendistroReportsKibana
          cp ./${{ env.PLUGIN_NAME }}-*.zip ./linux/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-linux-x64.zip
          mv ./${{ env.PLUGIN_NAME }}-*.zip ./windows/${{ env.PLUGIN_NAME }}-${{ env.OD_VERSION }}-windows-x64.zip

          cd linux
          wget https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/download/chromium-1.12.0.0/chromium-linux.zip
          unzip chromium-linux.zip -d ./kibana/opendistroReportsKibana
          zip -ur ./${{ env.PLUGIN_NAME }}-*.zip ./kibana
          mv ./${{ env.PLUGIN_NAME }}-*.zip ..
          cd ..

          cd windows
          wget https://github.com/opendistro-for-elasticsearch/kibana-reports/releases/download/chromium-1.12.0.0/chromium-windows.zip
          unzip chromium-windows.zip -d ./kibana/opendistroReportsKibana
          zip -ur ./${{ env.PLUGIN_NAME }}-*.zip ./kibana
          mv ./${{ env.PLUGIN_NAME }}-*.zip ..
          cd ..

          artifact=`ls ./${{ env.PLUGIN_NAME }}-*.zip`

          aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/kibana-plugins/opendistro-reports/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/downloads/*"
